In [1]:
%%HTML
<style>
.rendered_html table, .rendered_html th, .rendered_html tr, .rendered_html td {
     font-size: 100%;
}
</style>

# Metody Numeryczne

## Równania liniowe – rozkład LU



### dr hab. inż. Jerzy Baranowski, Prof.AGH

In [2]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
def normalize_vector(v):
    v=np.array(v)
    return v/np.linalg.norm(v)
import matplotlib as mpl
plt.style.context('seaborn-white')
mpl.rcParams['figure.dpi']= 200

## Jakie układy równań jest łatwo rozwiązać?

$$\LARGE
\mathbf{A}=
\begin{bmatrix}
a_{11}&a_{12}&a_{13}&\dots&a_{1n}\\
0&a_{22}&a_{23}&\dots&a_{2n}\\
0&0&a_{23}&\dots&a_{3n}\\
\vdots&\vdots&\vdots&\ddots&\vdots\\
0 & 0 & 0 & \dots & a_{nn}
\end{bmatrix}
$$

## Układ równań z macierzą trójkątną

- Bardzo proste wzory (tzw. podstawienie wsteczne, ang. backward substitution)

$$
\begin{aligned}
x_n ={}& \frac{b_n}{a_{nn}}\\
x_{n-1} ={}& \frac{b_{n-1}-x_n a_{n-1,n}}{a_{n-1,n-1}}\\
x_{n-2} ={}& \frac{b_{n-2}-x_{n-2} a_{n-2,n-1}-x_n a_{n-2,n}}{a_{n-2,n-2}}\\
{}&\vdots\\
x_1={}&\cfrac{b_1 - \sum\limits_{k=2}^n x_k a_{2k} }{a_{11}}
\end{aligned}
$$

- Mała złożoność $O(n^2)$
- Stabilność wsteczna

## Modyfikacja układu równań - dekompozycja

W praktyce, aby rozwiązać układ równań stosujemy dekompozycję macierzy

$$ \mathbf{A}=\mathbf{CD} $$

Układ ma wtedy postać

$$
\mathbf{A} \mathbf{x}= \mathbf{CD} \mathbf{x} = \mathbf{b}
$$
i rozwiązanie wyznaczamy jako
$$
\left\{
\begin{aligned}
\mathbf{D} \mathbf{x}= \mathbf{y}\\
\mathbf{C} \mathbf{y}= \mathbf{b}\\
\end{aligned}    
\right.
$$
Jeżeli $\mathbf{D}$ i $\mathbf{C}$ są trójkątne, lub w inny sposób łatwe do odwrócenia układ równań można łatwo rozwiązać


## Rozkład LU

Najpopularniejszym sposobem rozwiązywania układów równań liniowych jest rozkład LU

$$
\Huge \mathbf{A} = \mathbf{LU}
$$

gdzie, $\mathbf{L}$ jest macierzą trójkątną dolną (z 1 na przekątnej), $\mathbf{U}$ jest trójkątna górna

## Eliminacja gaussa

Rozkład LU konstruuje się przez eliminację Gaussa
$$\require{color}$$

$$
\underbrace{\mathbf{L}_{n-1}\dots \mathbf{L}_2 \mathbf{L}_1}_{\mathbf{L}^{-1}}\mathbf{A}=\mathbf{U}
$$

$$
\mathbf{L}=\mathbf{L}^{-1}_{1}\mathbf{L}^{-1}_{2}\dots \mathbf{L}^{-1}_{n-1}
$$

$$
\begin{array}{ccccccc}
\underset
{\mathbf{A}}
{
\begin{bmatrix}
\times&\times&\times&\times\\
\times&\times&\times&\times\\
\times&\times&\times&\times\\
\times&\times&\times&\times\\
\end{bmatrix}}
&
 \xrightarrow{\mathbf{L_1}} 
&
\underset
{\mathbf{\mathbf{L_1}\mathbf{A}}}
{
\begin{bmatrix}
\times&\times&\times&\times\\
\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
\end{bmatrix}}
&
 \xrightarrow{\mathbf{L_2}} 
&
\underset
{\mathbf{\mathbf{L_2}\mathbf{L_1}\mathbf{A}}}
{ 
\begin{bmatrix}
\times&\times&\times&\times\\
&\times&\times&\times\\
&\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
&\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
\end{bmatrix}}
&
\xrightarrow{\mathbf{L_3}} 
&
\underset
{\mathbf{\mathbf{L_3}\mathbf{L_2}\mathbf{L_1}\mathbf{A}}}
{ 
\begin{bmatrix}
\times&\times&\times&\times\\
&\times&\times&\times\\
&&\times&\times\\
&&\textcolor{red}{0}&\textcolor{red}{\times}\\
\end{bmatrix}}
\end{array}
 $$

## Konstrukcja macierzy $\mathbf{L}_k$

$$
\LARGE
\mathbf{L}_k = \begin{bmatrix}
1&&&&&\\
&\ddots&&&&\\
&&1&&&\\
&&-\ell_{k+1,k}&1&&\\
&&\vdots&&\ddots&\\
&&-\ell_{n,k}&&&1
\end{bmatrix}
$$

Gdzie 
$$
\ell_{jk} = \frac{\alpha_{jk}}{\alpha_{kk}},\ k<j\leq n
$$
przy czym $\alpha_{jk}$ są elementami macierzy $\mathbf{L_{k-1}}\dots\mathbf{L_1}\mathbf{A}$

## Macierz L

Na szczęście nie trzeba odwracać żadnych macierzy

$$\LARGE
\mathbf{L}=\mathbf{L}^{-1}_{1}\mathbf{L}^{-1}_{2}\dots \mathbf{L}^{-1}_{n-1}=
\begin{bmatrix}
1&&&&\\
\ell_{21}&1&&&\\
\ell_{31}&\ell_{32}&1&&\\
\vdots&\vdots&\ddots&\ddots&\\
\ell_{n1}&\ell_{n2}&\ldots&\ell_{n,n-1}&1
\end{bmatrix}
$$

## Naiwny algorytm LU

In [3]:
def naiveLU(A):
    n=len(A)
    U=A.copy()
    L=np.identity(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k]=U[j,k]/U[k,k]
            U[j,k:n]=U[j,k:n]-L[j,k]*U[k,k:n]
    return L,U

In [4]:
A = np.random.rand(4,4)
l,u = naiveLU(A)
print(l@u - A)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 2.22044605e-16  1.11022302e-16  0.00000000e+00  0.00000000e+00]]


## Niestabilność naiwnej metody

- Jeżeli w macierzy będą 0 w niewłaściwych miejscach to eliminacja będzie niemożliwa
- Jeżeli zamiast zer będą bardzo małe liczby jest duży potencjał na błędy numeryczne.

## Przykład

$$\mathbf{A} = \begin{bmatrix}10^{-20}&1\\1&1\end{bmatrix}$$



In [5]:
A = np.array([[1e-20,1],[1,1]])
l,u = naiveLU(A)


print(l@u-A)


[[ 0.  0.]
 [ 0. -1.]]


## Analitycznie 

 $$\mathbf{L} = \begin{bmatrix}1&0\\10^{20}&1\end{bmatrix}\quad \mathbf{U} = \begin{bmatrix}10^{-20}&1\\0&1-10^{20}\end{bmatrix}$$

## Numerycznie


In [6]:
print(l)
print(u)
print(1-1e20)

[[1.e+00 0.e+00]
 [1.e+20 1.e+00]]
[[ 1.e-20  1.e+00]
 [ 0.e+00 -1.e+20]]
-1e+20


## Pivoting (przestawianie)

Wybieramy wiersz zaczynający się od największego elementu i zamieniamy go z bieżącym

$$
\begin{bmatrix}
\times&\times&\times&\times&\times\\
&\times&\times&\times&\times\\
&\times&\times&\times&\times\\
&\textcolor{red}{\alpha_{ik}}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
&\times&\times&\times&\times
\end{bmatrix}
\xrightarrow{\mathbf{P}_1}
\begin{bmatrix}
\times&\times&\times&\times&\times\\
&\textcolor{red}{\alpha_{ik}}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
&\times&\times&\times&\times\\
&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
&\times&\times&\times&\times
\end{bmatrix}
\xrightarrow{\mathbf{L}_1}
\begin{bmatrix}
\times&\times&\times&\times&\times\\
&{\alpha_{ik}}&\times&\times&\times\\
&\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
&\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}\\
&\textcolor{red}{0}&\textcolor{red}{\times}&\textcolor{red}{\times}&\textcolor{red}{\times}
\end{bmatrix}
$$

$$
\mathbf{L}_{n-1}\mathbf{P}_{n-1}\dots \mathbf{L}_2\mathbf{P}_2 \mathbf{L}_1\mathbf{P}_1\mathbf{A}=\mathbf{U}
$$

Ze względu na własności $\mathbf{P}$ zachodzi:

$$
\Huge \mathbf{PA=LU}
$$




In [ ]:
def pivotingLU(A):
    n=len(A)
    U=A.copy().astype(float)
    L=np.identity(n)
    P=np.identity(n)
    for k in range(n-1):
        max_ind = np.argmax(np.abs(U[k:n,k]))+k #indeks maksymalnego elementu
        U[[k,max_ind],k:n]=U[[max_ind,k],k:n] #zamiana wierszy
        L[[k,max_ind],:k]=L[[max_ind,k],:k] #zamiana wierszy
        P[[k,max_ind],:]=P[[max_ind,k],:] #zamiana wierszy 
        for j in range(k+1,n): #elimnacja 
            L[j,k]=U[j,k]/U[k,k]
            U[j,k:n]=U[j,k:n]-L[j,k]*U[k,k:n]
    return L,U,P


In [21]:
from IPython.display import clear_output

In [43]:
def pivotingLU(A,displayU=False):
    n=len(A)
    U=A.copy().astype(float)
    L=np.identity(n)
    P=np.identity(n)
    for k in range(n-1):
        max_ind = np.argmax(np.abs(U[k:n,k]))+k
        

        U[[k,max_ind],k:n]=U[[max_ind,k],k:n]
        if displayU:
            input("Press Enter to continue...")
            clear_output()
            print('numer przestawionego wiersza:{}'.format(max_ind+1))           
            lista_macierzy=['P_{}L_{}'.format(k+1,k) for l in range(k)]
            nazwa_macierzy='macierz :'+"".join(lista_macierzy)+'P_1A'
            print(nazwa_macierzy)
            print(U)

        L[[k,max_ind],:k]=L[[max_ind,k],:k]
        P[[k,max_ind],:]=P[[max_ind,k],:]
        
        for j in range(k+1,n):
            L[j,k]=U[j,k]/U[k,k]
            pom = U[j,k:n]-L[j,k]*U[k,k:n]
            U[j,k:n]=pom
    if displayU:
        input("Press Enter to continue...")
        clear_output()
        lista_macierzy=['P_{}L_{}'.format(k+1,k) for l in range(k)]
        nazwa_macierzy='macierz :L{}'.format(n-1)+"".join(lista_macierzy)+'P_1A'
        print(nazwa_macierzy)
        print(U)    

    return L,U,P

In [44]:
A=np.array([[2,1,1,0],[4,3,3,1],[8, 7,9,5],[6,7,9,8]])
print('macierz A:')
print(A)
l,u,p = pivotingLU(A,True)

macierz :L3P_3L_2P_3L_2P_1A
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]


In [46]:
print('macierz U:')
print(u)
print('macierz L:')
print(l)
print('macierz P:')
print(p)

macierz U:
[[ 8.          7.          9.          5.        ]
 [ 0.          1.75        2.25        4.25      ]
 [ 0.          0.         -0.85714286 -0.28571429]
 [ 0.          0.          0.          0.66666667]]
macierz L:
[[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [ 0.5        -0.28571429  1.          0.        ]
 [ 0.25       -0.42857143  0.33333333  1.        ]]
macierz P:
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [49]:
print('PA-LU:')
print(p@A-l@u)

PA-LU:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Uwagi o LU
- Złożoność obliczeniowa rozkładu LU to $O\left(\frac{2}{3}n^3\right)$
- LU z pivotingiem jest stabilna wstecznie (stała uwarunkowania mnoży rząd błędu) dla wszystkich praktycznych macierzy
- stała uwarunkowania układu równań:
$$
\kappa=\frac{\sigma_1}{\sigma_n}
$$

- Istnieją macierze, w których elementy A i U mają różne rzędy wielkości (U dużo większy), takie macierze muszą mieć bardzo specyficzną strukturę i praktycznie nie występują w zastosowaniach

## Co z macierzą odwrotną?
- Rzadko, ale czasami potrzebujemy macierzy odwrotnej
- Wyznaczenie takiej macierzy jest równoważne rozwiązaniu n układów równań

$$
\mathbf{A} \mathbf{x}^{(i)}=\mathbf{e}_i 
$$
- Złożoność wprost to $O\left(\frac{2}{3}n^3 + 2n\cdot n^2\right)=O\left(\frac{8}{3}n^3 \right)$
- Możemy skorzystać z faktu, że mamy sporo zer w układzie równań i zredukować odrobinę złożoność - do $O(2n^3)$